In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("/content/Crop Production data.csv")

In [ ]:
df

State_Name District_Name  Crop_Year       Season  \
0      Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
1      Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
2      Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
3      Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
4      Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
...                            ...           ...        ...          ...   
34292                        Bihar       KATIHAR       2014  Rabi          
34293                        Bihar       KATIHAR       2014  Rabi          
34294                        Bihar       KATIHAR       2014  Summer        
34295                        Bihar       KATIHAR       2014  Summer        
34296                        Bihar       KATIHAR       2014    Summer      

                      Crop     Area  Production  
0                 Arecanut   1254.0      2000.0  
1      Other Kharif pulses      2.0         1.0  
2                     Rice    102.0       321.0  
3                   Banana    176.0       641.0  
4                Cashewnut    720.0       165.0  
...                    ...      ...         ...  
34292            Sunflower    964.0      1401.0  
34293                Wheat  39459.0     69873.0  
34294                Maize  20299.0    110570.0  
34295    Moong(Green Gram)   3512.0      4060.0  
34296                  NaN      NaN         NaN  

[34297 rows x 7 columns]

In [ ]:
df.isna().sum()

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34297 entries, 0 to 34296
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State_Name     34297 non-null  object 
 1   District_Name  34297 non-null  object 
 2   Crop_Year      34297 non-null  int64  
 3   Season         34297 non-null  object 
 4   Crop           34296 non-null  object 
 5   Area           34296 non-null  float64
 6   Production     34213 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.8+ MB


In [ ]:
df['Production'].mean()

592937.5865036682

In [ ]:
df.fillna("592937.5865036682",inplace = True)

In [ ]:
df.Production.value_counts()

Production
1.0         537
2.0         389
3.0         319
4.0         311
5.0         256
           ... 
301197.0      1
14789.0       1
3524.0        1
5644.0        1
110570.0      1
Name: count, Length: 12248, dtype: int64

In [ ]:
df.dtypes

State_Name        object
District_Name     object
Crop_Year          int64
Season            object
Crop              object
Area             float64
Production       float64
dtype: object

In [ ]:
df['Production'] = pd.to_numeric(df['Production'])

In [ ]:
df['Area'].max()

877029.0

In [ ]:
df["Area"] = pd.to_numeric(df['Area'])

In [ ]:
df['Area'].dtype

dtype('O')

In [ ]:
df['Area'].unique()

array([1254.0, 2.0, 102.0, ..., 39459.0, 20299.0, '592937.5865036682'],
      dtype=object)

In [ ]:
df.columns

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='object')

In [ ]:
df.Crop_Year.unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2010, 1997, 1998, 1999,
       2007, 2008, 2009, 2011, 2012, 2013, 2014])

In [ ]:
df.Production.mean()

592937.5865036682

In [ ]:
df.Production.median()

815.0

In [ ]:
df.describe()

Crop_Year           Area    Production
count  34297.000000   34297.000000  3.429700e+04
mean    2005.961338    7398.668707  5.929376e+05
std        5.122459   28752.244273  1.484681e+07
min     1997.000000       0.200000  0.000000e+00
25%     2002.000000      90.000000  1.120000e+02
50%     2006.000000     506.000000  8.150000e+02
75%     2011.000000    2705.000000  6.949000e+03
max     2014.000000  877029.000000  7.801620e+08

In [ ]:
# Q-1 which states have the production below average  ?
((df[(df['Production'] <592937.5865036682)])['State_Name']).unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar'], dtype=object)

In [ ]:
#Q-2 which states have highest area but production is below average
(df[(df['Production'] <592937.5865036682) & (df['Area'] == 877029.000000)])['State_Name'].unique()
#Ans andhra pradesh has crop_production below average in the year of 2005.

array(['Andhra Pradesh'], dtype=object)

In [ ]:
# Q-3 which years have crop_production below average in the states having highest area?
(df[(df['Production'] <592937.5865036682) & (df['Area'] == 877029.000000)])['Crop_Year'].unique()

array([2005])

In [ ]:
df.columns

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='object')

In [ ]:
df.describe()

Crop_Year           Area    Production
count  34297.000000   34297.000000  3.429700e+04
mean    2005.961338    7398.668707  5.929376e+05
std        5.122459   28752.244273  1.484681e+07
min     1997.000000       0.200000  0.000000e+00
25%     2002.000000      90.000000  1.120000e+02
50%     2006.000000     506.000000  8.150000e+02
75%     2011.000000    2705.000000  6.949000e+03
max     2014.000000  877029.000000  7.801620e+08

In [ ]:
len(df.District_Name.unique()) # total districts are 76

76

In [ ]:
len(df[(df.Production <= 1.120000e+02)]['District_Name'].unique())

75

In [ ]:
#Q-4 how many states in india having a crop production below or equal to 25%
df[(df.Production <= 1.120000e+02)]['Crop_Year'].unique()
#aNS almost every year

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2010, 1997, 1998, 1999,
       2008, 2009, 2011, 2012, 2013, 2014, 2007])